# Starter pipeline
# trigger:
# - main

pool: "Default"

# config azure machine test
# pool:
#   vmImage: ubuntu-latest

steps:

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'BUILD PROJECT GRADLE'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: 'ibanezstudio'
    projectKey: 'IbanezStudio_DevOps-foundation-v3'
    projectName: 'DevOps-foundation-v3'
  displayName: PREPARE SONARCLOUD SCANNER

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false

