apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-spring-deployment
  labels:
    app: microservice-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-spring
  template:
    metadata:
      labels:
        app: microservice-spring
    spec:
      containers:
      - name: microservice-spring
        image: estebanibannezp/spring-devops-image:latest
        ports:
        - containerPort: 8080